### ISSUE TITLE
Setting User causing artisan route command to fail

### ISSUE THREAD

**Issue by kidshenlong** [lucadegasperi/oauth2-server-laravel#338]
Setting a user object or using the Auth Facade in the constructor to allow user specific content. ie `$this->user->articles()`

    class RandomController {
        protected $user;
        public function __construct(){
        	$this->user = User::findOrFail(Authorizer::getResourceOwnerId());
        	//Auth::loginUsingId(Authorizer::getResourceOwnerId());
        }
    }

This has worked fine but artisan commands (` php artisan route:list`) are failing with `[Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to a member function getSession() on null`

I imagine because the constructor's running when the routes are queried... The issue doesn't persist if I set this in the individual route methods. But this feels hugely inefficient. Is there a prefered way of setting a user that would prevent this issue?

**Comment by lucadegasperi** [comment]
How is this related to this package?

**Comment by kidshenlong** [comment]
Sorry I guess I wasn't too clear. My issue is similar to https://github.com/lucadegasperi/oauth2-server-laravel/issues/194 in that `Authorizer::getResourceOwnerId()` doesn't really fail gracefully. 

There's a solution posted on that issue that appears to do this but it looks a bit hacky.

**Comment by lucadegasperi** [comment]
Before calling the getResourceOwnerId method, you need to call the ```oauth``` filter on the route. That filter will populate the Authorizer object.

**Comment by kidshenlong** [comment]
I'm calling oauth filter on the route. The issue only appears when running `php artisan route:list`

**Comment by spronkey** [comment]
Is the Auth::user() method / $request->user() method supposed to work with this package? If not, why not?

It seems non idiomatic for APIs that provide data customised to the current user to have to use Authorizer::getResourceOwnerId(), then find the user based on that.

**Comment by lucadegasperi** [comment]
Nope, it is not meant to work with Auth::user() or $request->user. why? Because in OAuth both a client or a user could be the resource owners, for Example on one endpoint that only clients use, the resource owner would be "1" and the resource owner type would be "client" on another endpoint, the resource owner could be still "1" but the resource owner type would be "user". Thus it is better to keep the oauth stuff separated from the regular auth things (which on a side note might as well set cookies and other headers you don't want back in an API endpoint because of its stateless nature)
