### ISSUE TITLE
validate users can have what scopes

### ISSUE THREAD

**Issue by finalight** [lucadegasperi/oauth2-server-laravel#344]
I intend to store all the different type of users into one single table, with a column to indicate what are the role of these users.

I notice that for this oauth2, there's a scope parameter, which will define what route can be access based on the scope given.

however, how do I check whether the users can have this scope or not?

I tried an experiment:

![screen shot 2015-04-11 at 3 40 48 am](https://cloud.githubusercontent.com/assets/4475526/7095383/948d77d0-dffc-11e4-8305-981605a52050.png)

----

and then after that...

![screen shot 2015-04-11 at 3 41 20 am](https://cloud.githubusercontent.com/assets/4475526/7095388/a3fed164-dffc-11e4-8bdc-19c60ee1d9eb.png)

----

clearly, this is very dangerous, since the users can impersonate as clients they shouldn't be able to and thus, access other routes.

So how do I prevent this?

**Comment by lucadegasperi** [comment]
Scopes and roles have nothing to do with each other. Scopes describes which data the client is going to be able to see and edit about the user.
Roles define what the user can do on the system. Since the client acts on user's behalf the client can only do what the user can do.
There are then some special kind of clients you can define which don't act on user's behalf but are able to modify the user's role.

**Comment by finalight** [comment]
so where do I actually enforce the role system and therefore, induce the scope from it?

**Comment by lucadegasperi** [comment]
After the access token is validated, you can retrieve the user associated to it. Once you've got the user you will be able to retrieve its role and act accordingly.
