### ISSUE TITLE
Use of a proxy

### ISSUE THREAD

**Issue by ismaelaarab** [lucadegasperi/oauth2-server-laravel#446]
How do i use a proxy to hide the secrets from the frontend?
Is this included in the package?

**Comment by hkmix** [comment]
The client should have a backend component which shouldn't reveal anything to the user. You won't need to hide anything, in that case.

**Comment by ismaelaarab** [comment]
And the component on the backend is a proxy?

**Comment by cmosguy** [comment]
@ismaelaarab  and @hkmix I am trying to understand this as well.  Can you please elaborate on how to do this with the package?

**Comment by hkmix** [comment]
@cmosguy What exactly are you trying to hide?

**Comment by cmosguy** [comment]
@hkmix i am trying to understand how to implement the backend as a proxy with this package.  I have read the article here: http://alexbilbie.com/2014/11/oauth-and-javascript/ but what I have failed to understand is how to go about implementing this proxy in NGINX or in PHP.

Am I supposed to do the proxy at PHP level?  Also how do I send Cookie: is that header or is that built into the request?

```
GET /ajax/resource/123 HTTP/1.1
Cookie: <encrypted cookie with tokens>
Host: example.com
```

**Comment by hkmix** [comment]
@cmosguy You implement it at the site level, using whatever language/framework you prefer. You can use PHP or anything else. Nginx is just the HTTP server. Interact with the cookie as per the language, so for PHP: http://php.net/manual/en/features.cookies.php

The idea is to run a backend server with your client secret that processes requests in between the frontend and the OAuth server. The backend will hold the client secret and encrypt and decrypt the cookie. You can also use a database to store the token info and use sessions instead of cookies.

**Comment by ismaelaarab** [comment]
@cmosguy Here is a tutorial that can help you. They use guzzle package to create the proxy. http://esbenp.github.io/2015/05/26/lumen-web-api-oauth-2-authentication/

Here is another package for handling the proxy but it's only for laravel 4. https://github.com/thinkingmik/api-proxy-laravel

**Comment by cmosguy** [comment]
@ismaelaarab and @hkmix thanks so much for your help.  I am going to go over these links.  I think I now have a better understanding of how to attack this proxy problem.

Cheers!

**Comment by pavankataria** [comment]
@cmosguy were you able to get it up and running?

**Comment by cmosguy** [comment]
@pavankataria sort of... I went in a different direction because the project got nixed.  will circle back at another time.
