### ISSUE TITLE
Verify user from DB for each request

### ISSUE THREAD

**Issue by tellsaqib** [lucadegasperi/oauth2-server-laravel#539]
I am using this package in Laravel 5.1 with Password grant. My issue is that any user can be marked as blocked in DB by admins. So I need to check user status in each and every call. What would be the best practice to achieve this?

**Comment by ddelnano** [comment]
Don't allow them to get an access token once they are blocked. And if they have a current access token invalidate it when the admin "block" occurs

**Comment by tellsaqib** [comment]
@ddelnano Blocking user occurs outside my Laravel application. That other system has access to DB. So should I remove all rows from oauth_sessions where owner_id = user_id of blocked user ?

**Comment by vinkla** [comment]
You could validate if the user is blocked or not in a middleware before issuing a new access token.

**Comment by tellsaqib** [comment]
@vinkla As I am using Password granth so I do check user details when issuing a new token. The problem is when user is blocked by admin after the token is issued.

**Comment by vinkla** [comment]
With a middleware you could fetch the access token owner id and compare it with your database.

**Comment by ddelnano** [comment]
@tellsaqib yes that is exactly what I would do.  If you don't do it that way the only way I would see it going otherwise would be the have a check for if the user is blocked after the OAuth middleware but your allowing a user that shouldn't have access in the first place to cause more queries on your database so why not stop them at the earliest point.

This is why I feel that blocking them from receiving an access token and when a user gets blocked removing all active tokens associated with them is the right approach.

**Comment by tellsaqib** [comment]
@vinkla Thanks for the help. Task accomplished using middleware.

**Comment by vinkla** [comment]
:+1:
