### ISSUE TITLE
Update Wiki, Laravel 5 installation

### ISSUE THREAD

**Issue by gaomd** [lucadegasperi/oauth2-server-laravel#544]
`lucadegasperi/oauth2-server-laravel` 5.0.1 was released, we should update [Wiki page](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation) to point to `5.0.*` instead of `5.0.*@dev`

The permission to edit the wiki page has been set to collaborators now, I'm unable to edit it.

**Comment by vinkla** [comment]
Thanks! Fixed.

**Comment by gaomd** [comment]
@vinkla We should also update all instances of class string to class constant to honor Laravel 5.1 coding style.


    'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider',

to 

    LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider::class,

**Comment by vinkla** [comment]
Personally I like registering it with a string. I'll leave it like that for now. Thanks.

**Comment by gaomd** [comment]
I think project consistency comes before presonal taste (for a project with 1000+ stars), it looks ugly when registering with string, and does not benefit the great feature for higher version of PHP.

![screen shot 2015-09-09 at 17 21 21](https://cloud.githubusercontent.com/assets/113737/9758133/4084b74c-5717-11e5-90a6-89b4fb81ea17.png)

**Comment by vinkla** [comment]
This is totally up to the developer. If they want to register with `::class` notation they can do that.

**Comment by gaomd** [comment]
I totally agree it's up to the developer, but since it's a package *for* Laravel 5.1, integrating more seemlessly to Laravel 5.1 **by default** would be a huge plus.

**Comment by vinkla** [comment]
> integrating more seamlessly to Laravel 5.1

This is only a matter of syntax preference. It will work either way.

**Comment by AJMiller** [comment]
+1 as a new(er) user of Laravel I found the wiki more confusing because there were 20+ lines above the insert point that followed the ::class syntax. In all honesty, I immediately thought "oh these instructions must be outdated". Would it be better to at least make note of the syntax alternative? IMO, it's much easier to follow along with install instructions that follow the coding conventions of the files they are inserting code into or at least mention that even though the install instructions follow a different convention it's 'ok' and won't screw up the rest of your app. It makes the user feel more confident that they're doing the right thing.

**Comment by vinkla** [comment]
Okay, I'll add it to the docs as soon as I've time. Thanks.

**Comment by vinkla** [comment]
Done.
