### ISSUE TITLE
Retrieve user at same auth endpoint

### ISSUE THREAD

**Issue by luciano-masuero** [lucadegasperi/oauth2-server-laravel#608]
I am using Laravel 5.1 and your awesome package.

What I am trying to achieve (if possible) is to do a Authorizer::issueAccessToken() and at the same time return user owner of that token.

Is possible that same endpoint that authenticate users returns something like:
```
{
  "access_token": "AkNqlCza6pGveoOB6Dfags4KzlvYwz1JIQdsFxSm",
  "token_type":"Bearer",
  "expires_in":3600
  "user": {
     ....
  }
}
```

**Comment by vinkla** [comment]
You can edit the JSON however you want. But instead it would be better to create a new endpoint which is called `/api/users/self` or something similar. This would be equlent with requesting a specific user by their ID `/api/users/{id}`. Instead of fetching the ID you have to check the access token's owner ID to find out which user it is. Please note that this will only work with the `password` grant or any other user grant.

**Comment by luciano-masuero** [comment]
@vinkla ok. I think that I was able to avoid this endpoint. Thanks for the answer. I think this can get closed..

**Comment by vinkla** [comment]
Okay, good.
