### ISSUE TITLE
How to return the items in this class in laravel 5 using the oauth 2.0?

### ISSUE THREAD

**Issue by adhip49** [lucadegasperi/oauth2-server-laravel#686]
I have used laravel 5.2 and oauth 2.0 but i had an error so i had to change the callbacks to this class but when i do that i go the error

{"error":"invalid_client","error_description":"Client authentication failed."}

I think its because nothing is returned

This is oauth 2.o .php page

'grant_types' => [

    'password' => [

        'class' => '\League\OAuth2\Server\Grant\PasswordGrant',

        'callback' => '\App\PasswordVerifier@verify',

        'access_token_ttl' => 3600
    ]
],
this is PasswordVerifier.php page

<?php
namespace App;

use Illuminate\Support\Facades\Auth;

class PasswordVerifier
{
public function verify($username, $password)
{
    $credentials =
        [
            'email' => $username,
            'password' => $password,
        ];

    if (Auth::once($credentials)) {
        return Auth::user()->id;
    } else {
        return false;
    }
        return verify;
}
}
    ?>

**Comment by SwiTool** [comment]
What is your exact problem ?
What are you searching to do ?

**Comment by adhip49** [comment]
I need to return some thing right ? the last statement return verify , i think its not correct !

**Comment by adhip49** [comment]
The main problem is i am getting this error

{"error":"invalid_client","error_description":"Client authentication failed."}

**Comment by SwiTool** [comment]
Ah. 
You should note return "verify". Btw what is it?
There is an if/else with a return inside both, it means that everything underneath won't be executed.

You need to return the resource owner id. But thats what you are doing if credentials are correct.

Client auth filed means that you specified a wrong client. Check the oauth_client table.
Since your grant type is password, you will need to provide:
grant_type: password
client_id: your client id populated in oauth_client table (if table empty, create yor own client)
client_secret: same for secret field
username: your laravel user account (email)
password: your laravel password

**Comment by vinkla** [comment]
Thanks for using this package! 

For this kind of support questions, we'd like you to use the following resources:  

- [Documentation](https://github.com/lucadegasperi/oauth2-server-laravel/tree/master/docs)
- [OAuth 2.0 Documentation](http://oauth2.thephpleague.com/)
- [Laracasts](https://laracasts.com/discuss)
- [Laravel Slack](https://larachat.co/)
- [Stack Overflow](http://stackoverflow.com/questions/tagged/laravel) 

This will allow us to keep the issues for bug reporting only and make our work easier.
